export interface IconOption {
  value: string;
  label: string;
}

// Icons for checklists and checklist groups
export const ICON_OPTIONS: IconOption[] = [
  { value: 'receipt', label: 'Receipt' },
  { value: 'shopping_cart', label: 'Shopping Cart' },
  { value: 'credit_card', label: 'Credit Card' },
  { value: 'account_balance_wallet', label: 'Wallet' },
  { value: 'paid', label: 'Paid' },
  { value: 'payments', label: 'Payments' },
  { value: 'request_quote', label: 'Request Quote' },
  { value: 'attach_money', label: 'Money' },
  { value: 'monetization_on', label: 'Monetization' },
  { value: 'savings', label: 'Savings' },
  { value: 'account_balance', label: 'Bank' },
  { value: 'trending_up', label: 'Increase' },
  { value: 'trending_down', label: 'Decrease' },
  { value: 'bar_chart', label: 'Chart' },
  { value: 'pie_chart', label: 'Pie Chart' },
  { value: 'euro', label: 'Euro' },
  { value: 'currency_exchange', label: 'Currency Exchange' },
  { value: 'local_atm', label: 'ATM' },
  { value: 'money_off', label: 'Money Off' },
  { value: 'attach_file', label: 'Attachment' },
  { value: 'local_grocery_store', label: 'Grocery Store' },
  { value: 'restaurant', label: 'Restaurant' },
  { value: 'local_dining', label: 'Dining' },
  { value: 'commute', label: 'Commute' },
  { value: 'local_gas_station', label: 'Gas Station' },
  { value: 'directions_car', label: 'Car' },
  { value: 'flight', label: 'Flight' },
  { value: 'hotel', label: 'Hotel' },
  { value: 'home', label: 'Home' },
  { value: 'work', label: 'Work' },
  { value: 'business_center', label: 'Business' },
  { value: 'medical_services', label: 'Medical' },
  { value: 'local_pharmacy', label: 'Pharmacy' },
  { value: 'school', label: 'School' },
  { value: 'subscriptions', label: 'Subscriptions' },
  { value: 'wifi', label: 'Internet' },
  { value: 'phone_android', label: 'Phone' },
  { value: 'movie', label: 'Movie' },
  { value: 'music_note', label: 'Music' },
  { value: 'sports_esports', label: 'Games' },
  { value: 'pets', label: 'Pets' },
  { value: 'child_friendly', label: 'Children' },
  { value: 'local_offer', label: 'Offer' },
  { value: 'local_cafe', label: 'Cafe' },
  { value: 'local_bar', label: 'Bar' },
  { value: 'event', label: 'Event' },
  { value: 'spa', label: 'Spa' },
  { value: 'health_and_safety', label: 'Health & Safety' },
  { value: 'emoji_transportation', label: 'Transportation' },
  { value: 'construction', label: 'Repairs' },
  { value: 'shopping_bag', label: 'Shopping Bag' },
  { value: 'local_laundry_service', label: 'Laundry' },
  { value: 'cleaning_services', label: 'Cleaning' },
  { value: 'subscriptions', label: 'Subscription' },
  { value: 'fact_check', label: 'Bills' },
  { value: 'directions_bus', label: 'Bus' },
  { value: 'two_wheeler', label: 'Two Wheeler' },
  { value: 'delivery_dining', label: 'Delivery' },
  { value: 'wine_bar', label: 'Wine Bar' },
  { value: 'sports_bar', label: 'Sports Bar' },
  { value: 'icecream', label: 'Ice Cream' },
  { value: 'smoking_rooms', label: 'Smoking' },
  { value: 'beach_access', label: 'Beach' },
  { value: 'local_hospital', label: 'Hospital' },
];
