export interface IconOption {
  value: string;
  label: string;
}

// Icons for checklists and checklist groups
export const CHECKLIST_ICON_OPTIONS: IconOption[] = [
  { value: 'checklist', label: 'Checklist' },
  { value: 'camping', label: 'Camping' },
  { value: 'backpack', label: 'Backpack' },
  { value: 'hiking', label: 'Hiking' },
  { value: 'sports', label: 'Sports' },
  { value: 'fitness_center', label: 'Fitness' },
  { value: 'restaurant', label: 'Restaurant' },
  { value: 'shopping_cart', label: 'Shopping' },
  { value: 'work', label: 'Work' },
  { value: 'school', label: 'School' },
  { value: 'home', label: 'Home' },
  { value: 'flight', label: 'Travel' },
  { value: 'beach_access', label: 'Beach' },
  { value: 'snowboarding', label: 'Winter Sports' },
  { value: 'directions_bike', label: 'Biking' },
  { value: 'pool', label: 'Pool' },
  { value: 'music_note', label: 'Music' },
  { value: 'book', label: 'Books' },
  { value: 'local_movies', label: 'Movies' },
  { value: 'videogame_asset', label: 'Games' },
  { value: 'checkroom', label: 'Checkroom' },
  { value: 'medical_services', label: 'Medical Services' },
  { value: 'person', label: 'Person' },
  { value: 'sports_esports', label: 'Sports Esports' },
  { value: 'build', label: 'Build' },
  { value: 'folder', label: 'Folder' },
  { value: 'folder_special', label: 'Special Folder' },
  { value: 'category', label: 'Category' },
  { value: 'label', label: 'Label' },
  { value: 'bookmark', label: 'Bookmark' },
  { value: 'collections', label: 'Collections' },
  { value: 'inventory_2', label: 'Inventory' },
  { value: 'archive', label: 'Archive' },
];

// Icons for checklist items (includes "None" option)
export const CHECKLIST_ITEM_ICON_OPTIONS: IconOption[] = [
  { value: '', label: 'None' },
  // { value: 'check_circle', label: 'Check Circle' },
  // { value: 'radio_button_unchecked', label: 'Unchecked' },
  { value: 'star', label: 'Star' },
  { value: 'favorite', label: 'Favorite' },
  { value: 'bookmark', label: 'Bookmark' },
  { value: 'flag', label: 'Flag' },
  { value: 'label', label: 'Label' },
  { value: 'local_offer', label: 'Tag' },
  { value: 'shopping_bag', label: 'Shopping Bag' },
  { value: 'shopping_cart', label: 'Shopping Cart' },
  { value: 'backpack', label: 'Backpack' },
  { value: 'luggage', label: 'Luggage' },
  { value: 'toys', label: 'Toys' },
  { value: 'sports_soccer', label: 'Sports' },
  { value: 'pool', label: 'Pool' },
  { value: 'beach_access', label: 'Beach' },
  { value: 'camping', label: 'Camping' },
  { value: 'hiking', label: 'Hiking' },
  { value: 'directions_bike', label: 'Biking' },
  { value: 'restaurant', label: 'Restaurant' },
  { value: 'local_dining', label: 'Dining' },
  { value: 'hotel', label: 'Hotel' },
  { value: 'flight', label: 'Flight' },
  { value: 'directions_car', label: 'Car' },
  { value: 'phone', label: 'Phone' },
  { value: 'laptop', label: 'Laptop' },
  { value: 'camera', label: 'Camera' },
  { value: 'camera_alt', label: 'Camera Alt' },
  { value: 'headphones', label: 'Headphones' },
  { value: 'book', label: 'Book' },
  { value: 'menu_book', label: 'Menu Book' },
  { value: 'music_note', label: 'Music' },
  { value: 'movie', label: 'Movie' },
  { value: 'videogame_asset', label: 'Games' },
  { value: 'fitness_center', label: 'Fitness' },
  { value: 'snowboarding', label: 'Winter Sports' },
  { value: 'umbrella', label: 'Umbrella' },
  { value: 'wb_sunny', label: 'Sun' },
  { value: 'ac_unit', label: 'AC Unit' },
  { value: 'water_drop', label: 'Water' },
  { value: 'local_pharmacy', label: 'Pharmacy' },
  { value: 'medical_services', label: 'Medical' },
  { value: 'cleaning_services', label: 'Cleaning' },
  { value: 'home', label: 'Home' },
  { value: 'work', label: 'Work' },
  { value: 'school', label: 'School' },
  { value: 'airline_seat_flat', label: 'Airline Seat Flat' },
  { value: 'local_fire_department', label: 'Fire Department' },
  { value: 'light_mode', label: 'Light Mode' },
  { value: 'chair', label: 'Chair' },
  { value: 'lightbulb', label: 'Lightbulb' },
  { value: 'layers', label: 'Layers' },
  { value: 'soup_kitchen', label: 'Soup Kitchen' },
  { value: 'content_cut', label: 'Content Cut' },
  { value: 'local_cafe', label: 'Local Cafe' },
  { value: 'settings', label: 'Settings' },
  { value: 'receipt', label: 'Receipt' },
  { value: 'directions_walk', label: 'Directions Walk' },
  { value: 'thermostat', label: 'Thermostat' },
  { value: 'inventory_2', label: 'Inventory' },
  { value: 'back_hand', label: 'Back Hand' },
  { value: 'volume_up', label: 'Volume Up' },
  { value: 'map', label: 'Map' },
  { value: 'emergency', label: 'Emergency' },
  { value: 'flashlight_on', label: 'Flashlight On' },
  { value: 'bath', label: 'Bath' },
  { value: 'bug_report', label: 'Bug Report' },
  { value: 'dry_cleaning', label: 'Dry Cleaning' },
  { value: 'battery_charging_full', label: 'Battery Charging Full' },
  { value: 'sanitizer', label: 'Sanitizer' },
  { value: 'style', label: 'Style' },
  { value: 'sports_volleyball', label: 'Sports Volleyball' },
  { value: 'visibility', label: 'Visibility' },
  { value: 'cable', label: 'Cable' },
  { value: 'construction', label: 'Construction' },
  { value: 'tire_repair', label: 'Tire Repair' },
  { value: 'warning', label: 'Warning' },
  { value: 'charging_station', label: 'Charging Station' },
  { value: 'navigation', label: 'Navigation' },
  { value: 'build', label: 'Build' },
  { value: 'checkroom', label: 'Checkroom' },
  { value: 'person', label: 'Person' },
  { value: 'sports_esports', label: 'Sports Esports' },
];

// All unique icon values used in seed data (for validation)
export const SEED_DATA_ICONS: string[] = [
  'camping',
  'home',
  'hotel',
  'airline_seat_flat',
  'local_fire_department',
  'light_mode',
  'chair',
  'lightbulb',
  'layers',
  'restaurant',
  'soup_kitchen',
  'ac_unit',
  'water_drop',
  'content_cut',
  'local_cafe',
  'settings',
  'cleaning_services',
  'receipt',
  'checkroom',
  'directions_walk',
  'umbrella',
  'thermostat',
  'inventory_2',
  'back_hand',
  'pool',
  'medical_services',
  'volume_up',
  'build',
  'map',
  'emergency',
  'flashlight_on',
  'person',
  'bath',
  'wb_sunny',
  'bug_report',
  'dry_cleaning',
  'battery_charging_full',
  'sanitizer',
  'sports_esports',
  'menu_book',
  'style',
  'sports_volleyball',
  'camera_alt',
  'visibility',
  'cable',
  'construction',
  'tire_repair',
  'warning',
  'charging_station',
  'navigation',
];
